/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant shamResturant = new Restaurant("shamResturant",5,"middle");
        Review note = new Review("shamResturant","cool and delicious",5);
        System.out.println(note.toString());


        System.out.println(shamResturant.toString());
        shamResturant.addReview("good service","COOL AND delicious",2);
        System.out.println(shamResturant.toString());
        System.out.println();

    }
}