/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.io.*;
import java.nio.file.*;

public class App {
    public String getGreeting() {
        return "Check Error for Js Files error";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Path path = Paths.get("src/main/resources/gates.js");
        System.out.println(isThereError(path));
    }
    public static String isThereError(Path path) {

        String errorMassage = "";
        try {
            BufferedReader reader  = Files.newBufferedReader(path);
            String line = reader.readLine();
            int numLine = 1;
            while (line != null) {
                if (!line.endsWith(";") && !line.isEmpty() &&
                        !line.endsWith("{") && !line.endsWith("}") && !line.contains("if") && !line.contains("else")) {
                    errorMassage = errorMassage + "Line" + numLine + ": Missing semicolon.\n";
                }
                numLine++;
                line = reader.readLine();
            }

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return errorMassage;
    }
}