/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testResToString() {
        Restaurant r1 = new Restaurant("shamikh",5,"low");
        System.out.println(r1.toString());
        String note = r1.toString();
        assertEquals("Restaurant: shamikh \n" +
                " rating : 5.0 \n" +
                " price category: low$",note);
    }


    @Test void testReviewToString() {
        Review r1 = new Review("shamikh","RES",2);
        System.out.println(r1.toString());
        String note = r1.toString();
        assertEquals("the Restaurant "+"shamikh"+" "+"RES" + "voted " +"2" +" stars." ,note);


    }

    @Test void testAssociated() {
        Restaurant r1 = new Restaurant("bad", 5, "high");
        r1.addReview("good","mazen",5);
        r1.addReview("bad","majed",1);
        r1.reviewList.toString();
    }


    @Test void testAddReview(){
        Restaurant r1 = new Restaurant("mac",0,"low");
        Review r2 = new Review("good","abd",4);

        r1.addReview("good","abd",4);
        String note =r1.toString();
        System.out.println(note);

        assertEquals("Restaurant: mac \n" +
                " rating : 2.0 \n" +
                " price category: low$",note);

    }


}