/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test public void testcheckErroratJs(){

        Path pathGateJS = Paths.get("src/main/resources/gates.js");
        String resGateJS = "Line3: Missing semicolon.\n" +
                "Line13: Missing semicolon.\n" +
                "Line15: Missing semicolon.\n" +
                "Line26: Missing semicolon.\n" +
                "Line28: Missing semicolon.\n" +
                "Line32: Missing semicolon.\n" +
                "Line36: Missing semicolon.\n" +
                "Line40: Missing semicolon.\n" +
                "Line41: Missing semicolon.\n" +
                "Line50: Missing semicolon.\n" +
                "Line51: Missing semicolon.\n" +
                "Line59: Missing semicolon.\n" +
                "Line60: Missing semicolon.\n" +
                "Line61: Missing semicolon.\n" +
                "Line62: Missing semicolon.\n" +
                "Line64: Missing semicolon.\n" +
                "Line77: Missing semicolon.\n" +
                "Line78: Missing semicolon.\n" +
                "Line79: Missing semicolon.\n" +
                "Line80: Missing semicolon.\n" +
                "Line86: Missing semicolon.\n" +
                "Line88: Missing semicolon.\n" +
                "Line89: Missing semicolon.\n" +
                "Line90: Missing semicolon.\n" +
                "Line91: Missing semicolon.\n" +
                "Line92: Missing semicolon.\n" +
                "Line101: Missing semicolon.\n";

        Path pathFirstJS = Paths.get("src/main/resources/firstOne.js");
        String resFirstJS = "";

        Path pathSecondJS = Paths.get("src/main/resources/secondOne.js");
        String resSecondJS = "Line92: Missing semicolon.\n";

        Path pathThirdJS = Paths.get("src/main/resources/thirdOne.js");
        String resThirdJS = "Line59: Missing semicolon.\n" +
                "Line60: Missing semicolon.\n" +
                "Line61: Missing semicolon.\n" +
                "Line62: Missing semicolon.\n" +
                "Line82: Missing semicolon.\n" +
                "Line84: Missing semicolon.\n";
        Path pathFourthJS = Paths.get("src/main/resources/fourthOne.js");
        String resFourthJS = "Line5: Missing semicolon.\n" +
                "Line13: Missing semicolon.\n" +
                "Line15: Missing semicolon.\n" +
                "Line32: Missing semicolon.\n" +
                "Line36: Missing semicolon.\n" +
                "Line40: Missing semicolon.\n" +
                "Line51: Missing semicolon.\n" +
                "Line53: Missing semicolon.\n" +
                "Line55: Missing semicolon.\n" +
                "Line59: Missing semicolon.\n" +
                "Line60: Missing semicolon.\n" +
                "Line61: Missing semicolon.\n" +
                "Line62: Missing semicolon.\n" +
                "Line64: Missing semicolon.\n" +
                "Line65: Missing semicolon.\n" +
                "Line70: Missing semicolon.\n" +
                "Line71: Missing semicolon.\n" +
                "Line72: Missing semicolon.\n" +
                "Line73: Missing semicolon.\n" +
                "Line82: Missing semicolon.\n" +
                "Line88: Missing semicolon.\n" +
                "Line89: Missing semicolon.\n" +
                "Line90: Missing semicolon.\n" +
                "Line91: Missing semicolon.\n";

        Path pathFifthJS = Paths.get("src/main/resources/emptyOne.js");
        String resFifthJS = "";

        assertEquals(resGateJS, App.isThereError(pathGateJS));
        assertEquals(resFirstJS, App.isThereError(pathFirstJS));
        assertEquals(resSecondJS, App.isThereError(pathSecondJS));
        assertEquals(resThirdJS, App.isThereError(pathThirdJS));
        assertEquals(resFourthJS, App.isThereError(pathFourthJS));
        assertEquals(resFifthJS, App.isThereError(pathFifthJS));


    }

}